prefix s:     <http://schema.org/>
prefix won:   <https://w3id.org/won/core#>
prefix pay:   <https://w3id.org/won/payment#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

Select ?main ?amount ?currency ?receiver ?feepayer ?tax ?invoiceid ?expirationtime ?invoicedetails

where {
    ?main a s:Invoice ;
         s:accountId ?receiver ;
         s:totalPaymentDue ?totalPaymentDue .
    ?totalPaymentDue a s:CompoundPriceSpecification;
         s:price ?amount ;
         s:priceCurrency ?currency ;
     
     OPTIONAL { ?main pay:hasFeePayer ?feepayer }
     OPTIONAL { ?main pay:hasTax ?tax }
     OPTIONAL { ?main pay:hasInvoiceId ?invoiceid }
     OPTIONAL { ?main pay:hasExpirationTime ?expirationtime }
     OPTIONAL { ?main pay:hasInvoiceDetails ?invoicedetails } 
}